config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post 'users/authenticate' => 'users#authenticate_remote'
  get  'users/get_info/:auth_token' => 'users#provide_info'

  resources :users, except: [:new, :destroy]
  resources :sites

  scope controller: :users do
    get   'register' => :new, as: 'signup'
    get   'account'  => :show
    get   'settings' => :edit
    patch 'account'  => :update
  end

  scope controller: :sessions do
    get    'login'        => :new
    get    'login_remote' => :new_remote
    post   'login'        => :create
    delete 'signout'      => :destroy
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  class << self
    def digest(token)
      Digest::SHA1.hexdigest(token.to_s)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/models/login.rb
class Login < ApplicationRecord
  belongs_to :user
  belongs_to :site

  before_create :assign_auth_token

  private

    def assign_auth_token
      self.auth_token = self.class.digest(self.class.new_token)
    end
end

app/models/site.rb
class UrlValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    unless valid_url?(value)
      record.errors[attribute] << (options[:message] || "is not a valid HTTP URL")
    end
  end

  private
  
    def valid_url?(str)
      uri = URI.parse(str)
      uri.kind_of?(URI::HTTP) && !uri.host.nil?
    rescue URI::InvalidURIError
      false
    end
end

class Site < ApplicationRecord
  has_many :logins
  has_many :users, through: :logins

  before_create :assign_secret_key

  validates :name, presence: true, length: { maximum: 60 }
  validates :domain, :user_update_callback, :auth_token_callback, url: true

  def send_auth_token(auth_token)
    SendUserAuthTokenJob.perform_later(self, auth_token)    
  end

  private

    def assign_secret_key
      self.secret_key = self.class.digest(self.class.new_token)
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :logins
  has_many :sites, through: :logins

  before_save :downcase_email
  before_create :assign_auth_digest

  has_secure_password

  EMAIL_REGEX = /\A[\w+-]+(\.[\w-]+)*@[a-z\d-]+(\.[a-z\d-]+)*(\.[a-z]{2,4})\z/i

  validates :first_name, :last_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 50 },
    uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

  def auth_token
    @auth_token || (self.auth_token = self.class.new_token)
  end

  def auth_token=(token)
    @auth_token = token
    self.auth_digest = self.class.digest(token)
    save(validate: false) unless new_record?
    token
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def publish_changes
    PublishUserChangesJob.perform_later(self)
  end

  def info
    { first_name: self.first_name, last_name: self.last_name, email: self.email }
  end

  private

    def downcase_email
      email.downcase!
    end

    def assign_auth_digest
      self.auth_digest = self.class.digest(self.class.new_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pundit

  add_flash_types :success, :info, :warning, :danger

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  private

    def user_not_authorized
      redirect_to root_path, danger: not_authorized_message
    end

    def not_authorized_message
      t("#{controller_name.sub(/s\z/, '')}.#{action_name}", scope: 'pundit', default: :default)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action { authorize :session }

  layout 'layouts/remote', only: :new_remote

  def new
  end

  def new_remote
    @callback_url = Site.find_by(domain: request.referrer).try(:auth_token_callback)
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    
    if user.try(:authenticate, params[:password])
      sign_in(user, params[:keep_signed_in])
      redirect_to account_path
    else
      flash.now[:danger] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

    def user_not_authorized
      redirect_to root_path
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action { authorize Site }

  def index
    @sites = Site.order(:id).paginate(page: params[:page])
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to sites_path, success: 'Site added'
    else
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])    
    if @site.update_attributes(site_params)
      redirect_to sites_path, success: 'Site updated'
    else
      render :edit
    end
  end

  # def destroy
  # end

  private
  
    def site_params
      params.require(:site).permit(
        :name,
        :domain,
        :user_update_callback,
        :auth_token_callback
      )
    end

    def user_not_authorized
      redirect_to root_path
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to account_path if signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action { authorize User }
  skip_before_action :verify_authenticity_token, only: [:authenticate_remote, :provide_info]

  def index
    @users = User.order(:id).paginate(page: params[:page])
  end

  def show
    return @user = current_user unless params[:id]
    if current_user.admin?
      @user = User.find(params[:id])
      redirect_to account_path if @user == current_user
    else
      raise Pundit::NotAuthorizedError
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    return @user = current_user unless params[:id]
    if current_user.admin?
      @user = User.find(params[:id])
      redirect_to settings_path if @user == current_user
    else
      raise Pundit::NotAuthorizedError
    end
  end
  
  def update
    @user = params[:id] && current_user.admin? ? User.find(params[:id]) : current_user    
    if @user.update_attributes(user_params)
      @user.publish_changes
      redirect_to @user, success: 'Settings updated'
    else
      render :edit
    end
  end

  def authenticate_remote
    site = Site.find_by(secret_key: params[:secret_key])
    @user = User.find_by(email: params[:user][:email]).try(:authenticate, params[:user][:password])

    if site && @user
      unless @login = Login.where(user_id: @user.id, site_id: site.id).first
        @login = Login.create(user_id: @user.id, site_id: site.id)
      end
      render json: { auth_token: @login.auth_token }
    else
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end
  end

  def provide_info
    @user = Login.find_by(auth_token: params[:auth_token]).try(:user)
    if @user
      render json: @user.info
    else
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation
      )
    end

    def user_not_authorized
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user, keep_signed_in = nil)
    auth_token = user.auth_token
    if keep_signed_in == '1'
      cookies.permanent[:auth_token] = auth_token
    else
      cookies[:auth_token] = auth_token
    end
    self.current_user = user
  end

  def sign_out
    if current_user
      current_user.update_attribute(:auth_digest, User.digest(User.new_token))
      cookies.delete(:auth_token)
      self.current_user = nil
    end
  end

  def current_user
    @current_user ||= User.find_by(auth_digest: User.digest(cookies[:auth_token]))
  end

  def signed_in?
    !current_user.nil?
  end

  private

    def current_user=(user)
      @current_user = user
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  %div{ class: "alert alert-#{key}", role: 'alert' }
    %p= value.html_safe

app/views/layouts/_footer.html.haml
%footer
  .container

app/views/layouts/_head.html.haml
%head
  %meta{ charset: 'utf-8' }
  %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
  %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
  %title OneAuth
  = csrf_meta_tags
  = stylesheet_link_tag 'application', media: 'all', data: { 'turbolinks-track': 'reload' }
  = javascript_include_tag 'application', data: { 'turbolinks-track': 'reload' }
  /[if lt IE 9]
    %script{ src: 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js' }
    %script{ src: 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js' }

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-default.navbar.navbar-fixed-top
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{ type: 'button', 'aria-expanded': 'false', data: { toggle: 'collapse', target: '#navbar' } }
          %span.sr-only Toggle navigation
          - 3.times do
            %span.icon-bar
        = render 'layouts/logo'
      #navbar.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          = render (signed_in? ? 'layouts/navlinks_user' : 'layouts/navlinks_visitor')

app/views/layouts/_logo.html.haml
= link_to 'OneAuth', signed_in? ? account_path : root_path, { class: 'navbar-brand', id: 'logo' }

app/views/layouts/_navlinks_user.html.haml
- if current_user.admin?
  %li
    = link_to sites_path do
      %span.glyphicon.glyphicon-list
      Sites
  %li
    = link_to users_path do
      %span.glyphicon.glyphicon-user
      Users  

%li.dropdown
  = link_to '#', class: 'dropdown-toggle', id: 'account-dropdown', data: { toggle: 'dropdown' }, role: 'button' do
    #user-name= current_user.full_name    
    %span.caret
  %ul.dropdown-menu{ 'aria-labelledby': 'accountDropdown' }
    %li
      = link_to account_path do
        %span.glyphicon.glyphicon-cog
        Account
    %li.divider{ role: 'separator' }
    %li
      = link_to signout_path, method: :delete do
        %span.glyphicon.glyphicon-log-out
        Sign out

app/views/layouts/_navlinks_visitor.html.haml
%li
  = link_to login_path do
    %strong Log In

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    = render 'layouts/header'
    = render 'layouts/flash'
    .container
      .row.main
        .col-xs-12
          = yield
    = render 'layouts/footer'

app/views/layouts/remote.html.haml
!!!
%html
  = render 'layouts/head'
  %body    
    .container
      .row.main
        .col-xs-12
          = yield

app/views/shared/_validation_errors.html.haml
- errors = obj.errors.full_messages
- unless errors.empty?  
  %div{ class: 'alert alert-danger validation-errors', role: 'alert' }
    - errors.each do |error|
      - error[0] = error[0].capitalize.to_s
      = error
      %br

app/views/sites/_shared_form_fields.html.haml
.form-group
  = f.label :name, 'Name'
  = f.text_field :name, class: 'form-control'
.form-group
  = f.label :domain, 'Domain'
  = f.text_field :domain, class: 'form-control'
.form-group
  = f.label :user_update_callback, 'User Update Callback'
  = f.text_field :user_update_callback, class: 'form-control'
.form-group
  = f.label :auth_token_callback, 'Authentication Token Callback'
  = f.text_field :auth_token_callback, class: 'form-control'

app/views/sites/_site.html.haml
%tr{ class: 'clickable-row', 'data-href': site_path(id: site.id) }
  %td= site.id
  %td= site.name
  %td= site.domain
  %td= site.secret_key
  %td= site.user_update_callback
  %td= site.auth_token_callback
  %td= site.created_at.localtime.strftime('%b %-d %Y, %I:%M:%S %p')

app/views/sites/_sites.html.haml
.table-responsive
  %table.table.table-bordered.table-hover.text-nowrap
    %thead
      %tr
        %th ID
        %th Name
        %th Domain
        %th Secret Key
        %th Update Callback
        %th Auth Token Callback
        %th Added On
    %tbody
      = render @sites

.text-center
  = will_paginate @sites

app/views/sites/edit.html.haml
= render 'shared/validation_errors', obj: @site

%h2.text-center Edit Site

.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
  = form_for @site, html: { class: 'center-block' } do |f|
    = render 'shared_form_fields', f: f
    .form-group
      = link_to 'Cancel', :back, class: 'btn btn-primary'
      = f.submit 'Update', class: 'btn btn-primary'

app/views/sites/index.html.haml
%h2.text-center Sites

.form-group
  = link_to 'Add', new_site_path, class: 'btn btn-primary'

#sites
  = render 'sites'

app/views/sites/new.html.haml
= render 'shared/validation_errors', obj: @site

%h2.text-center Add Site

.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
  = form_for @site, html: { class: 'center-block' } do |f|
    = render 'shared_form_fields', f: f
    .form-group
      = link_to 'Cancel', :back, class: 'btn btn-primary'
      = f.submit 'Add', class: 'btn btn-primary'

app/views/sites/show.html.haml
%h2.text-center Site Details

.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
  .center-block
    .form-group
      %b Name
      %p= @site.name
    .form-group
      %b Secret Key
      %p= @site.secret_key
    .form-group
      %b Domain
      %p= @site.domain    
    .form-group
      %b User Update Callback
      %p= @site.user_update_callback
    .form-group
      %b Authentication Token Callback
      %p= @site.auth_token_callback
    .form-group
      = link_to 'Edit', edit_site_path(@site), class: 'btn btn-primary'

app/views/static_pages/home.html.haml
.jumbotron.text-center
  %h2 Welcome!
  %h4
    Please
    = link_to 'log in', login_path
    or
    = link_to 'create an account', signup_path

app/views/users/_shared_form_fields.html.haml
.form-group
  = f.label :first_name, 'First Name'
  = f.text_field :first_name, class: 'form-control'
.form-group
  = f.label :last_name, 'Last Name'
  = f.text_field :last_name, class: 'form-control'
.form-group
  = f.label :email, 'Email'
  = f.text_field :email, class: 'form-control'

app/views/users/_user.html.haml
%tr{ class: 'clickable-row', 'data-href': user_path(id: user.id) }
  %td= user.id
  %td= user.full_name
  %td= user.email
  %td= user.created_at.localtime.strftime('%b %-d %Y, %I:%M:%S %p')

app/views/users/_users.html.haml
.table-responsive
  %table.table.table-bordered.table-hover.text-nowrap
    %thead
      %tr
        %th ID
        %th Name
        %th Email
        %th Registered On
    %tbody
      = render @users

.text-center
  = will_paginate @users

app/views/users/edit.html.haml
= render 'shared/validation_errors', obj: @user

%h2.text-center Edit Account

.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
  = form_for @user, html: { class: 'center-block' } do |f|
    .form-group
      = f.label :first_name, 'First Name'
      = f.text_field :first_name, class: 'form-control'
    .form-group
      = f.label :last_name, 'Last Name'
      = f.text_field :last_name, class: 'form-control'
    .form-group
      = f.label :email
      = f.text_field :email, class: 'form-control'
    .form-group    
      = link_to 'Cancel', :back, class: 'btn btn-primary'
      = f.submit 'OK', class: 'btn btn-primary'

app/views/users/index.html.haml
%h2.text-center All Users

#users
  = render 'users'

app/views/users/new.html.haml
= render 'shared/validation_errors', obj: @user

%h2.text-center Create Account

.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
  = form_for @user, html: { class: 'center-block' } do |f|
    = render 'shared_form_fields', f: f
    .form-group
      = f.label :password, 'Password'
      = f.password_field :password, class: 'form-control'
    .form-group
      = f.label :password_confirmation, 'Retype Password'
      = f.password_field :password_confirmation, class: 'form-control'
    .form-group
      = f.submit 'Register', class: 'btn btn-primary'

app/views/users/show.html.haml
%h2.text-center Account Details

.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
  .center-block
    .form-group
      %b Name
      %p= @user.full_name
    .form-group
      %b Email
      %p= @user.email
    .form-group
      = link_to 'Edit', (@user == current_user ? settings_path : edit_user_path(@user)), class: 'btn btn-primary'